export const SET_CURRENT_VIEW = "SET_CURRENT_VIEW";

export const SET_STORIES = "SET_STORIES";
export const SET_STORY_BEING_READ = "SET_STORY_BEING_READ";
export const SET_CHAPTER = "SET_CHAPTER";

export const FETCH_STORIES_IN_PROGRESS = "FETCH_STORIES_IN_PROGRESS";

export const FETCH_CHAPTERS_IN_PROGRESS = "FETCH_CHAPTERS_IN_PROGRESS";